export const commitsMock = {
    "total_count": 10,
    "incomplete_results": false,
    "items": [
        {
            "url": "https://api.github.com/repos/facebook/react/commits/6cbf0f7fac772c3fd18706d73af00f3fd06a55b5",
            "sha": "6cbf0f7fac772c3fd18706d73af00f3fd06a55b5",
            "node_id": "MDY6Q29tbWl0MTAyNzAyNTA6NmNiZjBmN2ZhYzc3MmMzZmQxODcwNmQ3M2FmMDBmM2ZkMDZhNTViNQ==",
            "html_url": "https://github.com/facebook/react/commit/6cbf0f7fac772c3fd18706d73af00f3fd06a55b5",
            "comments_url": "https://api.github.com/repos/facebook/react/commits/6cbf0f7fac772c3fd18706d73af00f3fd06a55b5/comments",
            "commit": {
                "url": "https://api.github.com/repos/facebook/react/git/commits/6cbf0f7fac772c3fd18706d73af00f3fd06a55b5",
                "author": {
                    "date": "2022-05-03T17:12:23.000-04:00",
                    "name": "Ricky",
                    "email": "rickhanlonii@gmail.com"
                },
                "committer": {
                    "date": "2022-05-03T17:12:23.000-04:00",
                    "name": "GitHub",
                    "email": "noreply@github.com"
                },
                "message": "Fork ReactSymbols (#24484)\n\n* Fork ReactSymbols\r\n\r\n* Fix tests\r\n\r\n* Update jest config",
                "tree": {
                    "url": "https://api.github.com/repos/facebook/react/git/trees/47de3c1f8355c11c0655e9d3bbb2ae887a038a5c",
                    "sha": "47de3c1f8355c11c0655e9d3bbb2ae887a038a5c"
                },
                "comment_count": 0
            },
            "author": {
                "login": "rickhanlonii",
                "id": 2440089,
                "node_id": "MDQ6VXNlcjI0NDAwODk=",
                "avatar_url": "https://avatars.githubusercontent.com/u/2440089?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/rickhanlonii",
                "html_url": "https://github.com/rickhanlonii",
                "followers_url": "https://api.github.com/users/rickhanlonii/followers",
                "following_url": "https://api.github.com/users/rickhanlonii/following{/other_user}",
                "gists_url": "https://api.github.com/users/rickhanlonii/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/rickhanlonii/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rickhanlonii/subscriptions",
                "organizations_url": "https://api.github.com/users/rickhanlonii/orgs",
                "repos_url": "https://api.github.com/users/rickhanlonii/repos",
                "events_url": "https://api.github.com/users/rickhanlonii/events{/privacy}",
                "received_events_url": "https://api.github.com/users/rickhanlonii/received_events",
                "type": "User",
                "site_admin": false
            },
            "committer": {
                "login": "web-flow",
                "id": 19864447,
                "node_id": "MDQ6VXNlcjE5ODY0NDQ3",
                "avatar_url": "https://avatars.githubusercontent.com/u/19864447?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/web-flow",
                "html_url": "https://github.com/web-flow",
                "followers_url": "https://api.github.com/users/web-flow/followers",
                "following_url": "https://api.github.com/users/web-flow/following{/other_user}",
                "gists_url": "https://api.github.com/users/web-flow/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/web-flow/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/web-flow/subscriptions",
                "organizations_url": "https://api.github.com/users/web-flow/orgs",
                "repos_url": "https://api.github.com/users/web-flow/repos",
                "events_url": "https://api.github.com/users/web-flow/events{/privacy}",
                "received_events_url": "https://api.github.com/users/web-flow/received_events",
                "type": "User",
                "site_admin": false
            },
            "parents": [
                {
                    "url": "https://api.github.com/repos/facebook/react/commits/a10a9a6b5b891dd3ce238bf39a6147bb0f3a1d2a",
                    "html_url": "https://github.com/facebook/react/commit/a10a9a6b5b891dd3ce238bf39a6147bb0f3a1d2a",
                    "sha": "a10a9a6b5b891dd3ce238bf39a6147bb0f3a1d2a"
                }
            ],
            "repository": {
                "id": 10270250,
                "node_id": "MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==",
                "name": "react",
                "full_name": "facebook/react",
                "private": false,
                "owner": {
                    "login": "facebook",
                    "id": 69631,
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjY5NjMx",
                    "avatar_url": "https://avatars.githubusercontent.com/u/69631?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/facebook",
                    "html_url": "https://github.com/facebook",
                    "followers_url": "https://api.github.com/users/facebook/followers",
                    "following_url": "https://api.github.com/users/facebook/following{/other_user}",
                    "gists_url": "https://api.github.com/users/facebook/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/facebook/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/facebook/subscriptions",
                    "organizations_url": "https://api.github.com/users/facebook/orgs",
                    "repos_url": "https://api.github.com/users/facebook/repos",
                    "events_url": "https://api.github.com/users/facebook/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/facebook/received_events",
                    "type": "Organization",
                    "site_admin": false
                },
                "html_url": "https://github.com/facebook/react",
                "description": "A declarative, efficient, and flexible JavaScript library for building user interfaces.",
                "fork": false,
                "url": "https://api.github.com/repos/facebook/react",
                "forks_url": "https://api.github.com/repos/facebook/react/forks",
                "keys_url": "https://api.github.com/repos/facebook/react/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/facebook/react/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/facebook/react/teams",
                "hooks_url": "https://api.github.com/repos/facebook/react/hooks",
                "issue_events_url": "https://api.github.com/repos/facebook/react/issues/events{/number}",
                "events_url": "https://api.github.com/repos/facebook/react/events",
                "assignees_url": "https://api.github.com/repos/facebook/react/assignees{/user}",
                "branches_url": "https://api.github.com/repos/facebook/react/branches{/branch}",
                "tags_url": "https://api.github.com/repos/facebook/react/tags",
                "blobs_url": "https://api.github.com/repos/facebook/react/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/facebook/react/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/facebook/react/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/facebook/react/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/facebook/react/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/facebook/react/languages",
                "stargazers_url": "https://api.github.com/repos/facebook/react/stargazers",
                "contributors_url": "https://api.github.com/repos/facebook/react/contributors",
                "subscribers_url": "https://api.github.com/repos/facebook/react/subscribers",
                "subscription_url": "https://api.github.com/repos/facebook/react/subscription",
                "commits_url": "https://api.github.com/repos/facebook/react/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/facebook/react/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/facebook/react/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/facebook/react/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/facebook/react/contents/{+path}",
                "compare_url": "https://api.github.com/repos/facebook/react/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/facebook/react/merges",
                "archive_url": "https://api.github.com/repos/facebook/react/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/facebook/react/downloads",
                "issues_url": "https://api.github.com/repos/facebook/react/issues{/number}",
                "pulls_url": "https://api.github.com/repos/facebook/react/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/facebook/react/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/facebook/react/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/facebook/react/labels{/name}",
                "releases_url": "https://api.github.com/repos/facebook/react/releases{/id}",
                "deployments_url": "https://api.github.com/repos/facebook/react/deployments"
            },
            "score": 1
        },
        {
            "url": "https://api.github.com/repos/facebook/react/commits/4c03bb6ed01a448185d9a1554229208a9480560d",
            "sha": "4c03bb6ed01a448185d9a1554229208a9480560d",
            "node_id": "MDY6Q29tbWl0MTAyNzAyNTA6NGMwM2JiNmVkMDFhNDQ4MTg1ZDlhMTU1NDIyOTIwOGE5NDgwNTYwZA==",
            "html_url": "https://github.com/facebook/react/commit/4c03bb6ed01a448185d9a1554229208a9480560d",
            "comments_url": "https://api.github.com/repos/facebook/react/commits/4c03bb6ed01a448185d9a1554229208a9480560d/comments",
            "commit": {
                "url": "https://api.github.com/repos/facebook/react/git/commits/4c03bb6ed01a448185d9a1554229208a9480560d",
                "author": {
                    "date": "2022-05-13T21:54:50.000-07:00",
                    "name": "Luna Ruan",
                    "email": "lunaris.ruan@gmail.com"
                },
                "committer": {
                    "date": "2022-05-14T00:54:50.000-04:00",
                    "name": "GitHub",
                    "email": "noreply@github.com"
                },
                "message": "[DevTools] ignore tests without reactVersion pragma if REACT_VERSION specified (#24555)\n\nIn DevTools tests, if the REACT_VERSION specified, we know this is a regression test (testing older React Versions). Because a lot of tests test the DevTools front end and we don't want to run them in the regression test scenario, we decided to only run tests that have the // @reactVersion pragma defined.\r\n\r\nBecause if there are no tests specified, jest will fail, we also opt to use jest.skip to skip all the tests that we don't want to run for a specific React version istead.\r\n\r\nThis PR makes this change.",
                "tree": {
                    "url": "https://api.github.com/repos/facebook/react/git/trees/7afa485ee4c67a31b6f03069cb597320a1e16c8a",
                    "sha": "7afa485ee4c67a31b6f03069cb597320a1e16c8a"
                },
                "comment_count": 0
            },
            "author": {
                "login": "lunaruan",
                "id": 2735514,
                "node_id": "MDQ6VXNlcjI3MzU1MTQ=",
                "avatar_url": "https://avatars.githubusercontent.com/u/2735514?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/lunaruan",
                "html_url": "https://github.com/lunaruan",
                "followers_url": "https://api.github.com/users/lunaruan/followers",
                "following_url": "https://api.github.com/users/lunaruan/following{/other_user}",
                "gists_url": "https://api.github.com/users/lunaruan/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/lunaruan/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/lunaruan/subscriptions",
                "organizations_url": "https://api.github.com/users/lunaruan/orgs",
                "repos_url": "https://api.github.com/users/lunaruan/repos",
                "events_url": "https://api.github.com/users/lunaruan/events{/privacy}",
                "received_events_url": "https://api.github.com/users/lunaruan/received_events",
                "type": "User",
                "site_admin": false
            },
            "committer": {
                "login": "web-flow",
                "id": 19864447,
                "node_id": "MDQ6VXNlcjE5ODY0NDQ3",
                "avatar_url": "https://avatars.githubusercontent.com/u/19864447?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/web-flow",
                "html_url": "https://github.com/web-flow",
                "followers_url": "https://api.github.com/users/web-flow/followers",
                "following_url": "https://api.github.com/users/web-flow/following{/other_user}",
                "gists_url": "https://api.github.com/users/web-flow/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/web-flow/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/web-flow/subscriptions",
                "organizations_url": "https://api.github.com/users/web-flow/orgs",
                "repos_url": "https://api.github.com/users/web-flow/repos",
                "events_url": "https://api.github.com/users/web-flow/events{/privacy}",
                "received_events_url": "https://api.github.com/users/web-flow/received_events",
                "type": "User",
                "site_admin": false
            },
            "parents": [
                {
                    "url": "https://api.github.com/repos/facebook/react/commits/0ecb77d4c54664e20abd89df0d19ef4e4594f4c8",
                    "html_url": "https://github.com/facebook/react/commit/0ecb77d4c54664e20abd89df0d19ef4e4594f4c8",
                    "sha": "0ecb77d4c54664e20abd89df0d19ef4e4594f4c8"
                }
            ],
            "repository": {
                "id": 10270250,
                "node_id": "MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==",
                "name": "react",
                "full_name": "facebook/react",
                "private": false,
                "owner": {
                    "login": "facebook",
                    "id": 69631,
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjY5NjMx",
                    "avatar_url": "https://avatars.githubusercontent.com/u/69631?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/facebook",
                    "html_url": "https://github.com/facebook",
                    "followers_url": "https://api.github.com/users/facebook/followers",
                    "following_url": "https://api.github.com/users/facebook/following{/other_user}",
                    "gists_url": "https://api.github.com/users/facebook/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/facebook/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/facebook/subscriptions",
                    "organizations_url": "https://api.github.com/users/facebook/orgs",
                    "repos_url": "https://api.github.com/users/facebook/repos",
                    "events_url": "https://api.github.com/users/facebook/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/facebook/received_events",
                    "type": "Organization",
                    "site_admin": false
                },
                "html_url": "https://github.com/facebook/react",
                "description": "A declarative, efficient, and flexible JavaScript library for building user interfaces.",
                "fork": false,
                "url": "https://api.github.com/repos/facebook/react",
                "forks_url": "https://api.github.com/repos/facebook/react/forks",
                "keys_url": "https://api.github.com/repos/facebook/react/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/facebook/react/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/facebook/react/teams",
                "hooks_url": "https://api.github.com/repos/facebook/react/hooks",
                "issue_events_url": "https://api.github.com/repos/facebook/react/issues/events{/number}",
                "events_url": "https://api.github.com/repos/facebook/react/events",
                "assignees_url": "https://api.github.com/repos/facebook/react/assignees{/user}",
                "branches_url": "https://api.github.com/repos/facebook/react/branches{/branch}",
                "tags_url": "https://api.github.com/repos/facebook/react/tags",
                "blobs_url": "https://api.github.com/repos/facebook/react/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/facebook/react/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/facebook/react/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/facebook/react/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/facebook/react/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/facebook/react/languages",
                "stargazers_url": "https://api.github.com/repos/facebook/react/stargazers",
                "contributors_url": "https://api.github.com/repos/facebook/react/contributors",
                "subscribers_url": "https://api.github.com/repos/facebook/react/subscribers",
                "subscription_url": "https://api.github.com/repos/facebook/react/subscription",
                "commits_url": "https://api.github.com/repos/facebook/react/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/facebook/react/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/facebook/react/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/facebook/react/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/facebook/react/contents/{+path}",
                "compare_url": "https://api.github.com/repos/facebook/react/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/facebook/react/merges",
                "archive_url": "https://api.github.com/repos/facebook/react/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/facebook/react/downloads",
                "issues_url": "https://api.github.com/repos/facebook/react/issues{/number}",
                "pulls_url": "https://api.github.com/repos/facebook/react/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/facebook/react/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/facebook/react/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/facebook/react/labels{/name}",
                "releases_url": "https://api.github.com/repos/facebook/react/releases{/id}",
                "deployments_url": "https://api.github.com/repos/facebook/react/deployments"
            },
            "score": 1
        },
        {
            "url": "https://api.github.com/repos/facebook/react/commits/c5e039d9b0857b10fbcea861469ad0948c84b045",
            "sha": "c5e039d9b0857b10fbcea861469ad0948c84b045",
            "node_id": "MDY6Q29tbWl0MTAyNzAyNTA6YzVlMDM5ZDliMDg1N2IxMGZiY2VhODYxNDY5YWQwOTQ4Yzg0YjA0NQ==",
            "html_url": "https://github.com/facebook/react/commit/c5e039d9b0857b10fbcea861469ad0948c84b045",
            "comments_url": "https://api.github.com/repos/facebook/react/commits/c5e039d9b0857b10fbcea861469ad0948c84b045/comments",
            "commit": {
                "url": "https://api.github.com/repos/facebook/react/git/commits/c5e039d9b0857b10fbcea861469ad0948c84b045",
                "author": {
                    "date": "2022-05-16T08:30:43.000-07:00",
                    "name": "Luna Ruan",
                    "email": "lunaris.ruan@gmail.com"
                },
                "committer": {
                    "date": "2022-05-16T08:30:43.000-07:00",
                    "name": "GitHub",
                    "email": "noreply@github.com"
                },
                "message": "[DevTools] Add jest-cli --reactVersion argument (#24556)\n\nAdd `--reactVersion` argument. This argument is only used in DevTools. When this is specified, run only the tests that have the `// @reactVersion` pragma that satisfies the semver version range. Otherwise, run tests as normal",
                "tree": {
                    "url": "https://api.github.com/repos/facebook/react/git/trees/ea68a914302422a41d14af1e43c2a0c6a57e92d9",
                    "sha": "ea68a914302422a41d14af1e43c2a0c6a57e92d9"
                },
                "comment_count": 0
            },
            "author": {
                "login": "lunaruan",
                "id": 2735514,
                "node_id": "MDQ6VXNlcjI3MzU1MTQ=",
                "avatar_url": "https://avatars.githubusercontent.com/u/2735514?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/lunaruan",
                "html_url": "https://github.com/lunaruan",
                "followers_url": "https://api.github.com/users/lunaruan/followers",
                "following_url": "https://api.github.com/users/lunaruan/following{/other_user}",
                "gists_url": "https://api.github.com/users/lunaruan/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/lunaruan/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/lunaruan/subscriptions",
                "organizations_url": "https://api.github.com/users/lunaruan/orgs",
                "repos_url": "https://api.github.com/users/lunaruan/repos",
                "events_url": "https://api.github.com/users/lunaruan/events{/privacy}",
                "received_events_url": "https://api.github.com/users/lunaruan/received_events",
                "type": "User",
                "site_admin": false
            },
            "committer": {
                "login": "web-flow",
                "id": 19864447,
                "node_id": "MDQ6VXNlcjE5ODY0NDQ3",
                "avatar_url": "https://avatars.githubusercontent.com/u/19864447?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/web-flow",
                "html_url": "https://github.com/web-flow",
                "followers_url": "https://api.github.com/users/web-flow/followers",
                "following_url": "https://api.github.com/users/web-flow/following{/other_user}",
                "gists_url": "https://api.github.com/users/web-flow/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/web-flow/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/web-flow/subscriptions",
                "organizations_url": "https://api.github.com/users/web-flow/orgs",
                "repos_url": "https://api.github.com/users/web-flow/repos",
                "events_url": "https://api.github.com/users/web-flow/events{/privacy}",
                "received_events_url": "https://api.github.com/users/web-flow/received_events",
                "type": "User",
                "site_admin": false
            },
            "parents": [
                {
                    "url": "https://api.github.com/repos/facebook/react/commits/4c03bb6ed01a448185d9a1554229208a9480560d",
                    "html_url": "https://github.com/facebook/react/commit/4c03bb6ed01a448185d9a1554229208a9480560d",
                    "sha": "4c03bb6ed01a448185d9a1554229208a9480560d"
                }
            ],
            "repository": {
                "id": 10270250,
                "node_id": "MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==",
                "name": "react",
                "full_name": "facebook/react",
                "private": false,
                "owner": {
                    "login": "facebook",
                    "id": 69631,
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjY5NjMx",
                    "avatar_url": "https://avatars.githubusercontent.com/u/69631?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/facebook",
                    "html_url": "https://github.com/facebook",
                    "followers_url": "https://api.github.com/users/facebook/followers",
                    "following_url": "https://api.github.com/users/facebook/following{/other_user}",
                    "gists_url": "https://api.github.com/users/facebook/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/facebook/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/facebook/subscriptions",
                    "organizations_url": "https://api.github.com/users/facebook/orgs",
                    "repos_url": "https://api.github.com/users/facebook/repos",
                    "events_url": "https://api.github.com/users/facebook/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/facebook/received_events",
                    "type": "Organization",
                    "site_admin": false
                },
                "html_url": "https://github.com/facebook/react",
                "description": "A declarative, efficient, and flexible JavaScript library for building user interfaces.",
                "fork": false,
                "url": "https://api.github.com/repos/facebook/react",
                "forks_url": "https://api.github.com/repos/facebook/react/forks",
                "keys_url": "https://api.github.com/repos/facebook/react/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/facebook/react/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/facebook/react/teams",
                "hooks_url": "https://api.github.com/repos/facebook/react/hooks",
                "issue_events_url": "https://api.github.com/repos/facebook/react/issues/events{/number}",
                "events_url": "https://api.github.com/repos/facebook/react/events",
                "assignees_url": "https://api.github.com/repos/facebook/react/assignees{/user}",
                "branches_url": "https://api.github.com/repos/facebook/react/branches{/branch}",
                "tags_url": "https://api.github.com/repos/facebook/react/tags",
                "blobs_url": "https://api.github.com/repos/facebook/react/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/facebook/react/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/facebook/react/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/facebook/react/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/facebook/react/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/facebook/react/languages",
                "stargazers_url": "https://api.github.com/repos/facebook/react/stargazers",
                "contributors_url": "https://api.github.com/repos/facebook/react/contributors",
                "subscribers_url": "https://api.github.com/repos/facebook/react/subscribers",
                "subscription_url": "https://api.github.com/repos/facebook/react/subscription",
                "commits_url": "https://api.github.com/repos/facebook/react/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/facebook/react/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/facebook/react/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/facebook/react/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/facebook/react/contents/{+path}",
                "compare_url": "https://api.github.com/repos/facebook/react/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/facebook/react/merges",
                "archive_url": "https://api.github.com/repos/facebook/react/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/facebook/react/downloads",
                "issues_url": "https://api.github.com/repos/facebook/react/issues{/number}",
                "pulls_url": "https://api.github.com/repos/facebook/react/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/facebook/react/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/facebook/react/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/facebook/react/labels{/name}",
                "releases_url": "https://api.github.com/repos/facebook/react/releases{/id}",
                "deployments_url": "https://api.github.com/repos/facebook/react/deployments"
            },
            "score": 1
        },
    ]
}