export const repositoriesMock = {
    "total_count": 2409103,
    "incomplete_results": false,
    "items": [
        {
            "id": 10270250,
            "node_id": "MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==",
            "name": "react",
            "full_name": "facebook/react",
            "private": false,
            "owner": {
                "login": "facebook",
                "id": 69631,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjY5NjMx",
                "avatar_url": "https://avatars.githubusercontent.com/u/69631?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/facebook",
                "html_url": "https://github.com/facebook",
                "followers_url": "https://api.github.com/users/facebook/followers",
                "following_url": "https://api.github.com/users/facebook/following{/other_user}",
                "gists_url": "https://api.github.com/users/facebook/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/facebook/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/facebook/subscriptions",
                "organizations_url": "https://api.github.com/users/facebook/orgs",
                "repos_url": "https://api.github.com/users/facebook/repos",
                "events_url": "https://api.github.com/users/facebook/events{/privacy}",
                "received_events_url": "https://api.github.com/users/facebook/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/facebook/react",
            "description": "A declarative, efficient, and flexible JavaScript library for building user interfaces.",
            "fork": false,
            "url": "https://api.github.com/repos/facebook/react",
            "forks_url": "https://api.github.com/repos/facebook/react/forks",
            "keys_url": "https://api.github.com/repos/facebook/react/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/facebook/react/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/facebook/react/teams",
            "hooks_url": "https://api.github.com/repos/facebook/react/hooks",
            "issue_events_url": "https://api.github.com/repos/facebook/react/issues/events{/number}",
            "events_url": "https://api.github.com/repos/facebook/react/events",
            "assignees_url": "https://api.github.com/repos/facebook/react/assignees{/user}",
            "branches_url": "https://api.github.com/repos/facebook/react/branches{/branch}",
            "tags_url": "https://api.github.com/repos/facebook/react/tags",
            "blobs_url": "https://api.github.com/repos/facebook/react/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/facebook/react/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/facebook/react/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/facebook/react/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/facebook/react/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/facebook/react/languages",
            "stargazers_url": "https://api.github.com/repos/facebook/react/stargazers",
            "contributors_url": "https://api.github.com/repos/facebook/react/contributors",
            "subscribers_url": "https://api.github.com/repos/facebook/react/subscribers",
            "subscription_url": "https://api.github.com/repos/facebook/react/subscription",
            "commits_url": "https://api.github.com/repos/facebook/react/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/facebook/react/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/facebook/react/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/facebook/react/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/facebook/react/contents/{+path}",
            "compare_url": "https://api.github.com/repos/facebook/react/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/facebook/react/merges",
            "archive_url": "https://api.github.com/repos/facebook/react/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/facebook/react/downloads",
            "issues_url": "https://api.github.com/repos/facebook/react/issues{/number}",
            "pulls_url": "https://api.github.com/repos/facebook/react/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/facebook/react/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/facebook/react/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/facebook/react/labels{/name}",
            "releases_url": "https://api.github.com/repos/facebook/react/releases{/id}",
            "deployments_url": "https://api.github.com/repos/facebook/react/deployments",
            "created_at": "2013-05-24T16:15:54Z",
            "updated_at": "2022-09-13T16:46:58Z",
            "pushed_at": "2022-09-13T16:22:15Z",
            "git_url": "git://github.com/facebook/react.git",
            "ssh_url": "git@github.com:facebook/react.git",
            "clone_url": "https://github.com/facebook/react.git",
            "svn_url": "https://github.com/facebook/react",
            "homepage": "https://reactjs.org",
            "size": 183318,
            "stargazers_count": 194673,
            "watchers_count": 194673,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": true,
            "forks_count": 40225,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 1094,
            "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": "MDc6TGljZW5zZTEz"
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
                "declarative",
                "frontend",
                "javascript",
                "library",
                "react",
                "ui"
            ],
            "visibility": "public",
            "forks": 40225,
            "open_issues": 1094,
            "watchers": 194673,
            "default_branch": "main",
            "score": 1
        },
        {
            "id": 135786093,
            "node_id": "MDEwOlJlcG9zaXRvcnkxMzU3ODYwOTM=",
            "name": "react",
            "full_name": "typescript-cheatsheets/react",
            "private": false,
            "owner": {
                "login": "typescript-cheatsheets",
                "id": 50188264,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjUwMTg4MjY0",
                "avatar_url": "https://avatars.githubusercontent.com/u/50188264?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/typescript-cheatsheets",
                "html_url": "https://github.com/typescript-cheatsheets",
                "followers_url": "https://api.github.com/users/typescript-cheatsheets/followers",
                "following_url": "https://api.github.com/users/typescript-cheatsheets/following{/other_user}",
                "gists_url": "https://api.github.com/users/typescript-cheatsheets/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/typescript-cheatsheets/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/typescript-cheatsheets/subscriptions",
                "organizations_url": "https://api.github.com/users/typescript-cheatsheets/orgs",
                "repos_url": "https://api.github.com/users/typescript-cheatsheets/repos",
                "events_url": "https://api.github.com/users/typescript-cheatsheets/events{/privacy}",
                "received_events_url": "https://api.github.com/users/typescript-cheatsheets/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/typescript-cheatsheets/react",
            "description": "Cheatsheets for experienced React developers getting started with TypeScript",
            "fork": false,
            "url": "https://api.github.com/repos/typescript-cheatsheets/react",
            "forks_url": "https://api.github.com/repos/typescript-cheatsheets/react/forks",
            "keys_url": "https://api.github.com/repos/typescript-cheatsheets/react/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/typescript-cheatsheets/react/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/typescript-cheatsheets/react/teams",
            "hooks_url": "https://api.github.com/repos/typescript-cheatsheets/react/hooks",
            "issue_events_url": "https://api.github.com/repos/typescript-cheatsheets/react/issues/events{/number}",
            "events_url": "https://api.github.com/repos/typescript-cheatsheets/react/events",
            "assignees_url": "https://api.github.com/repos/typescript-cheatsheets/react/assignees{/user}",
            "branches_url": "https://api.github.com/repos/typescript-cheatsheets/react/branches{/branch}",
            "tags_url": "https://api.github.com/repos/typescript-cheatsheets/react/tags",
            "blobs_url": "https://api.github.com/repos/typescript-cheatsheets/react/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/typescript-cheatsheets/react/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/typescript-cheatsheets/react/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/typescript-cheatsheets/react/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/typescript-cheatsheets/react/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/typescript-cheatsheets/react/languages",
            "stargazers_url": "https://api.github.com/repos/typescript-cheatsheets/react/stargazers",
            "contributors_url": "https://api.github.com/repos/typescript-cheatsheets/react/contributors",
            "subscribers_url": "https://api.github.com/repos/typescript-cheatsheets/react/subscribers",
            "subscription_url": "https://api.github.com/repos/typescript-cheatsheets/react/subscription",
            "commits_url": "https://api.github.com/repos/typescript-cheatsheets/react/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/typescript-cheatsheets/react/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/typescript-cheatsheets/react/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/typescript-cheatsheets/react/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/typescript-cheatsheets/react/contents/{+path}",
            "compare_url": "https://api.github.com/repos/typescript-cheatsheets/react/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/typescript-cheatsheets/react/merges",
            "archive_url": "https://api.github.com/repos/typescript-cheatsheets/react/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/typescript-cheatsheets/react/downloads",
            "issues_url": "https://api.github.com/repos/typescript-cheatsheets/react/issues{/number}",
            "pulls_url": "https://api.github.com/repos/typescript-cheatsheets/react/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/typescript-cheatsheets/react/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/typescript-cheatsheets/react/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/typescript-cheatsheets/react/labels{/name}",
            "releases_url": "https://api.github.com/repos/typescript-cheatsheets/react/releases{/id}",
            "deployments_url": "https://api.github.com/repos/typescript-cheatsheets/react/deployments",
            "created_at": "2018-06-02T04:08:16Z",
            "updated_at": "2022-09-13T16:11:36Z",
            "pushed_at": "2022-09-13T11:53:37Z",
            "git_url": "git://github.com/typescript-cheatsheets/react.git",
            "ssh_url": "git@github.com:typescript-cheatsheets/react.git",
            "clone_url": "https://github.com/typescript-cheatsheets/react.git",
            "svn_url": "https://github.com/typescript-cheatsheets/react",
            "homepage": "https://react-typescript-cheatsheet.netlify.app",
            "size": 2747,
            "stargazers_count": 36414,
            "watchers_count": 36414,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": false,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": false,
            "forks_count": 3186,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 4,
            "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": "MDc6TGljZW5zZTEz"
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
                "cheatsheet",
                "guide",
                "react",
                "typescript"
            ],
            "visibility": "public",
            "forks": 3186,
            "open_issues": 4,
            "watchers": 36414,
            "default_branch": "main",
            "score": 1
        },
        {
            "id": 75396575,
            "node_id": "MDEwOlJlcG9zaXRvcnk3NTM5NjU3NQ==",
            "name": "react",
            "full_name": "duxianwei520/react",
            "private": false,
            "owner": {
                "login": "duxianwei520",
                "id": 3249653,
                "node_id": "MDQ6VXNlcjMyNDk2NTM=",
                "avatar_url": "https://avatars.githubusercontent.com/u/3249653?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/duxianwei520",
                "html_url": "https://github.com/duxianwei520",
                "followers_url": "https://api.github.com/users/duxianwei520/followers",
                "following_url": "https://api.github.com/users/duxianwei520/following{/other_user}",
                "gists_url": "https://api.github.com/users/duxianwei520/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/duxianwei520/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/duxianwei520/subscriptions",
                "organizations_url": "https://api.github.com/users/duxianwei520/orgs",
                "repos_url": "https://api.github.com/users/duxianwei520/repos",
                "events_url": "https://api.github.com/users/duxianwei520/events{/privacy}",
                "received_events_url": "https://api.github.com/users/duxianwei520/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/duxianwei520/react",
            "description": " React+webpack+redux+ant design+axios+less全家桶后台管理框架",
            "fork": false,
            "url": "https://api.github.com/repos/duxianwei520/react",
            "forks_url": "https://api.github.com/repos/duxianwei520/react/forks",
            "keys_url": "https://api.github.com/repos/duxianwei520/react/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/duxianwei520/react/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/duxianwei520/react/teams",
            "hooks_url": "https://api.github.com/repos/duxianwei520/react/hooks",
            "issue_events_url": "https://api.github.com/repos/duxianwei520/react/issues/events{/number}",
            "events_url": "https://api.github.com/repos/duxianwei520/react/events",
            "assignees_url": "https://api.github.com/repos/duxianwei520/react/assignees{/user}",
            "branches_url": "https://api.github.com/repos/duxianwei520/react/branches{/branch}",
            "tags_url": "https://api.github.com/repos/duxianwei520/react/tags",
            "blobs_url": "https://api.github.com/repos/duxianwei520/react/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/duxianwei520/react/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/duxianwei520/react/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/duxianwei520/react/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/duxianwei520/react/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/duxianwei520/react/languages",
            "stargazers_url": "https://api.github.com/repos/duxianwei520/react/stargazers",
            "contributors_url": "https://api.github.com/repos/duxianwei520/react/contributors",
            "subscribers_url": "https://api.github.com/repos/duxianwei520/react/subscribers",
            "subscription_url": "https://api.github.com/repos/duxianwei520/react/subscription",
            "commits_url": "https://api.github.com/repos/duxianwei520/react/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/duxianwei520/react/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/duxianwei520/react/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/duxianwei520/react/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/duxianwei520/react/contents/{+path}",
            "compare_url": "https://api.github.com/repos/duxianwei520/react/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/duxianwei520/react/merges",
            "archive_url": "https://api.github.com/repos/duxianwei520/react/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/duxianwei520/react/downloads",
            "issues_url": "https://api.github.com/repos/duxianwei520/react/issues{/number}",
            "pulls_url": "https://api.github.com/repos/duxianwei520/react/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/duxianwei520/react/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/duxianwei520/react/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/duxianwei520/react/labels{/name}",
            "releases_url": "https://api.github.com/repos/duxianwei520/react/releases{/id}",
            "deployments_url": "https://api.github.com/repos/duxianwei520/react/deployments",
            "created_at": "2016-12-02T13:08:43Z",
            "updated_at": "2022-09-13T08:11:25Z",
            "pushed_at": "2022-08-31T07:37:35Z",
            "git_url": "git://github.com/duxianwei520/react.git",
            "ssh_url": "git@github.com:duxianwei520/react.git",
            "clone_url": "https://github.com/duxianwei520/react.git",
            "svn_url": "https://github.com/duxianwei520/react",
            "homepage": "",
            "size": 3599,
            "stargazers_count": 4638,
            "watchers_count": 4638,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": true,
            "forks_count": 1683,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 8,
            "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": "MDc6TGljZW5zZTEz"
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
                "ant-design-pro",
                "antd",
                "babel",
                "es6",
                "es7",
                "react",
                "redux",
                "webpack"
            ],
            "visibility": "public",
            "forks": 1683,
            "open_issues": 8,
            "watchers": 4638,
            "default_branch": "master",
            "score": 1
        },
    ]
}